### ISSUE TITLE
Question about authenticating with email link

### ISSUE THREAD

**Issue by rodrigomata** [david-asher/electron-firebase#1]
Hey congratulations on the amazing repo, it is definitely very useful and has a lot of potential. I do however have a question because I don't see anywhere on the README nor the source code on how to use Firebase authentication with email link. Can you please tell me if this is possible with this package, and if so, a very simple explanation on how to achieve it? thanks!

**Comment by david-asher** [comment]
Hi Rodrigo, You are correct in that I didn't test every sign-in method, and Firebase keeps expanding the selection. All of that interaction is handled by the firebaseui layer, so email authentication should work. If you experience any difficulty, please report the problem and I will put attention to testing that aspect.

Please note that the app-config.json file should be edited to list only those authenticators that you would like to appear on the list that will be presented to the user.
