### ISSUE TITLE
FirebaseAuth Scopes/Methods

### ISSUE THREAD

**Issue by Calhistorian** [david-asher/electron-firebase#10]
After spending some time in the electron-firebase module, I am unsure whether I also need to manage user access to other Google API's separate from FirebaseAuth. 

I modified the scopes in the `idpConfig` variable to include Drive and Sheets

<img width="744" alt="CleanShot 2021-11-08 at 12 03 25@2x" src="https://user-images.githubusercontent.com/51142180/140810115-62cf4e28-540e-4d1e-84e9-6cdaad1be67b.png">

My assumption had been that I could use the `accessToken` to make API calls to either Drive or Sheets , but an `Error: Bad Request` is returned when using the below function:

<img width="663" alt="CleanShot 2021-11-08 at 12 05 20@2x" src="https://user-images.githubusercontent.com/51142180/140810298-cba5ec86-8269-4fc3-a1f6-f809d945e65f.png">

After doing some reading, I am skeptical whether I can use this token for authenticating other gapi's on behalf of the signed in user. Or did I miss a method already existing in the code?

**Comment by david-asher** [comment]
In the auth module, there's a function gcpApi(). Try using that to make the calls to GCP; it should handle all of the auth and refresh for you. Look in fbstorage.js for examples of using gcpApi().

**Comment by Calhistorian** [comment]
It looks like the auth is working, but I am not confident in the axios call. Getting 

error:

```
gcpApi:  {
  url: {
    protocol: 'https:',
    hostname: 'www.googleapis.com',
    pathname: 'drive/v3/files/1YmuVswG_Lj3GQp13RCmAGNzavBRT20Ncwk1trWVPdVg'
  },
  method: 'GET',
  headers: {
    authorization: 'Firebase {token}'
  }
}
gcpApi:  Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443,
  config: {
    url: 'https:://www.googleapis.com/drive/v3/files/1YmuVswG_Lj3GQp13RCmAGNzavBRT20Ncwk1trWVPdVg',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      authorization: 'Firebase {token}',
      'User-Agent': 'Chrome'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '://www.googleapis.com/drive/v3/files/1YmuVswG_Lj3GQp13RCmAGNzavBRT20Ncwk1trWVPdVg',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: null,
      port: null,
      nativeProtocols: [Object],
      pathname: '://www.googleapis.com/drive/v3/files/1YmuVswG_Lj3GQp13RCmAGNzavBRT20Ncwk1trWVPdVg'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET ://www.googleapis.com/drive/v3/files/1YmuVswG_Lj3GQp13RCmAGNzavBRT20Ncwk1trWVPdVg HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'authorization: Firebase {token}\r\n' +
        'User-Agent: Chrome\r\n' +
        'Host: localhost\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '://www.googleapis.com/drive/v3/files/1YmuVswG_Lj3GQp13RCmAGNzavBRT20Ncwk1trWVPdVg',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https:://www.googleapis.com/drive/v3/files/1YmuVswG_Lj3GQp13RCmAGNzavBRT20Ncwk1trWVPdVg',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
} {
  url: 'https://www.googleapis.com/drive/v3/files/1YmuVswG_Lj3GQp13RCmAGNzavBRT20Ncwk1trWVPdVg'
}
```

Just attempting to grab a drive file of the logged in user. I removed the token from the errors.

**Comment by david-asher** [comment]
In the response:
```
    headers: {
      Accept: 'application/json, text/plain, */*',
      authorization: 'Firebase {token}',
      'User-Agent': 'Chrome'
    },
```
gcpApi() is passing the Firebase token. Firebase isn't the same as other parts of GCP and it's not surprising that the Firebase token won't work. You were probably on the right track building your own googleDriveApi() function. There may be good news. Take a look inside the global.user object and you may find the token passed from the browser at login time.

**Comment by Calhistorian** [comment]
Thank you. I was unsure since I am not that familiar with axios. 

I did read somewhere (forgot now) that upon logging in to Firebase Auth you can call a specific method (or use a parameter) to return an apis token. Is this what you are referring to? Or should I just be looking for more than the `accessToken` and `refreshToken`? Thanks for all your help again. This framework is so well set up.

**Comment by david-asher** [comment]
The latter - you want the accessToken returned from the browser’s Google login workflow. I believe that the refreshToken isn’t available there, which is another issue we can deal with if you get the GCP call working with the accessToken.

**Comment by Calhistorian** [comment]
Ok. I was able to capture the OAuth Access token by capturing it in the initial login phase. I then manually used that token to authenticate and create a folder in Drive. So that is a success, thank you.

If I may also ask you a followup question. I am still somewhat lost in the services of the setup. I can see that you are sending the authentication credentials back to the main app through the `postAuthResult()` function in `weblogin.js`, and in fact passing that `authResult.credential` (which contains the OAuthToken) through an `api()` call. But I can't find where  the payload is sent to be destructured and saved in localDB and Firestore. I would like to send the oauthAccessToken (`authResult.credential.oauthAccessToken`) to the main process and store it. 

![weblogin.js postAuthResult](https://user-images.githubusercontent.com/51142180/141001129-fad5505f-d787-4917-a863-24f3699bf7d0.png)

Can you provide some insight as to the route that would help me do this?

Edit:

I was an idiot for a moment, but I see that you are passing the `authResult.credential` object, I just need help finding where that hits the main app so that I might extract it. It should contain the `authResult.credential.oauthAccessToken` mentioned above.

Edit:

Then with further discovery, Firebase Auth is unable to actually refresh that accessToken (at least that I can tell - is that true to your knowledge?). So it looks like I need to setup a whole parallel auth flow for the the Google APIs to refresh the accessToken.

**Comment by david-asher** [comment]
You are doing great! And yes, you will need to take care of refreshing the access token. I believe that the refresh token isn't available, however, these instructions from Google might enable you to request it in the authentication request. I'm not sure whether the FirebaseUI workflow gives you the opportunity to set the access_type according to these instructions, so you'll have to do some digging in the browser-side scripts.
https://developers.google.com/identity/protocols/oauth2/openid-connect#refresh-tokens

**Comment by Calhistorian** [comment]
So after some further digging, it seems that as of at least earlier this year - from what I can tell - getting any kind of refresh token is not possible through Firebase Auth. However, the workaround seems to be one of two solutions:

1. Use Google Sign-in for the web and use the access_token to sign in to Firebase
2. Manage Google APIs access separately. 

So when you have time, could you provide your opinion on your current setup. 

First, it seems like it would be a huge refactor to transition to Google Sign-In instead of FirebaseAuth - is that correct? My desire to use Firebase mainly stemmed from a desire to limit the management of a backend and allow for tracking users and syncing between devices.  

Second, the application I am building is highly focused on transparency and data ownership. Therefore, it isn't an inconvenience for me to actually manage Drive and Sheets scope separately through an onboarding process (funnily, I am picturing a UX similar to current macOS long chains of permissions through location services, folders, etc). If I go this route, any advice on piggy-backing on the already built infrastructure for FirebaseAuth -- truth-be-told, I LOVE the UX that you have setup in that regard.

Again, appreciate all your help here. As a teaser, I am building an app to bring data ownership to the many "tools for thought" applications out there. Have it working with google service accounts, but that is a horrible way to go about it.

**Comment by david-asher** [comment]
You've already got the Google login, you just need to get the refresh token, so try this. In module scripts/weblogin.js, function firebaseAuthUIStart(), the signInOptions{} object gets filled in with the information that FirebaseUI needs to configure the login workflow. Just before the call to firebaseui.auth.AuthUI(), look for the element that has the Google provider (sounds like it's the only one in your case). Add the access_type customParameters, like so:
```
signInOptions: [{
      provider: firebase.auth.GoogleAuthProvider.PROVIDER_ID,
      scopes: ['https://www.googleapis.com/auth/gmail.readonly'],
      customParameters: { access_type: 'offline' }
}]
```
Check that the postAuthResult() function gets the refresh token.

**Comment by Calhistorian** [comment]
Oh...thanks. Simple enough. Now the question becomes will it work for refreshing the oauth accessToken when it expires?

**Comment by david-asher** [comment]
Yep.
https://developers.google.com/identity/protocols/oauth2/web-server#offline

**Comment by Calhistorian** [comment]
I get an `invalid_grant` error when I do the post call. The access_token is good, as using `oauth2Client.getTokenInfo()` returns a valid status. I believe I have the syntax right with the post request. 


```
       let tokens = {
            client_id: CLIENT_ID,
            client_secret: CLIENT_SECRET,
            refresh_token: auth.refreshToken,
            // access_token: auth.accessToken,
            grant_type: 'refresh_token'
        }
        axios.post('https://oauth2.googleapis.com/token', tokens, 
            {
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded'
                }
            }
        ).then((res) => {
            console.log(res.data)
        }).catch((err) => {
            console.log(err)
        })
```

Now that I think of it, maybe the header isn't coming out right. 

<img width="444" alt="CleanShot 2021-11-10 at 11 46 47@2x" src="https://user-images.githubusercontent.com/51142180/141182805-393fdae8-f30c-450b-b80b-1724f64591c6.png">


I am still skeptical that this refresh token can refresh the oauthAccessToken. Am I wrong. Clearly you know better than I, but your earlier skepticism has me thinking that option 2 above that I suggested may be the only route here.

<img width="398" alt="CleanShot 2021-11-10 at 11 51 55@2x" src="https://user-images.githubusercontent.com/51142180/141183612-285806c2-3934-46ab-afa0-dcaf27be52be.png">

**Comment by david-asher** [comment]
I've implemented oauth2 with many providers and the refresh process has always been reliable. In your call, the data property looks suspicious as a json string instead of an object. I suggest that you use the applib.request() function instead of axios directly because it handles the user agent string. See the gcpApi() function in lib/authentication.js as an example. The interface to applib.request() is intended to mimic the [npm request](https://www.npmjs.com/package/request) module which has been deprecated but was a popular https client.

**Comment by Calhistorian** [comment]
Hmm.. Thanks. I went ahead and created a function in the module - modeled after the `gcpApi()` function.

```
async function refreshTokens( requestOptions )
{
    try {
        console.log( "refreshTokens - requestOptions: ", requestOptions )
        // synchronous API call
        const response = await applib.request( requestOptions )
        console.log( "refreshTokens - response: ", response )
        // a good response may be a bad response, so throw a fit
        if ( response.status >= 400 ) {
            throw( { error: response.statusText, code: response.status, message: response.data } )
        }

        // return the requested data
        return applib.parseJSON( response.data )
    }
    catch (error) {
        console.error( "refreshTokens: ", error, requestOptions )
        return error
    }
}
```

I structured the payload in the same format as that used in the `gcpApi()` function and I think according to OAuth parameters:

<img width="857" alt="CleanShot 2021-11-11 at 06 49 55@2x" src="https://user-images.githubusercontent.com/51142180/141318343-8e4eae16-cbbc-4eec-96a7-6cd79077813b.png">


```
let payload = {
                method: 'POST',
                url: {
                    hostname: 'oauth2.googleapis.com',
                    pathname: '/token',
                },
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                },
                body: {
                    refresh_token: auth.refresh_token,
                    client_id: auth.client_id,
                    client_secret: auth.client_secret,
                    grant_type: auth.grant_type,
                },

            }
```

Call the function
```
refreshTokens(payload).then(res => {
                console.log(res)
            })
```

Response: 
<img width="504" alt="CleanShot 2021-11-11 at 06 33 58@2x" src="https://user-images.githubusercontent.com/51142180/141317715-8328f65e-9bde-4ab7-8af8-932fe3e375e3.png">


Still says `invalid grant_type` - which as you know is basically a catch-all error.
```
request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST //token HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'User-Agent: Chrome\r\n' +
        'Content-Length: 1632\r\n' +
        'Host: oauth2.googleapis.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '//token',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'oauth2.googleapis.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: {
      error: 'unsupported_grant_type',
      error_description: 'Invalid grant_type: '
    }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
```

Because of your confidence, I can only imagine that my request parameters are inappropriate. 

EDIT:

I went ahead and dropped into Postman the appropriate parameters and I get the same error - "invalid_grant".

EDIT:

I should have caught this earlier, but the `refreshToken` returned in the images above that appeared after we switched the signin parameters is the same refreshToken from the FirebaseAuth return in the `stsTokenManager` object.

<img width="428" alt="CleanShot 2021-11-11 at 10 47 40@2x" src="https://user-images.githubusercontent.com/51142180/141352496-d3b15dd0-1b51-4581-a8d8-9e84e546e501.png">

**Comment by david-asher** [comment]
Welcome to the wonderfully frustrating world of authentication! Where every little imperfection results in the same non-helpful error response. Until it doesn't and everything works. You're getting close. 

The next debug part is a little tricky but is very powerful. When you set debugMode:true in app-config.json, all of the browser windows will start in Chrome debug mode. If you resize the windows you will be able to see the full Chrome debugger. You want to inspect the authResult object passed to postAuthResult() in scripts/weblogin.js. You can either breakpoint and inspect the object, or put a console.log() statement in the function (I find using the console output easier). I suggest taking the refreshToken from that response and use your Postman setup to test it.

**Comment by Calhistorian** [comment]
This is what I had done before. The refreshToken that I thought was different was just duplicated to a different location in the JSON object since I returned the object after you restructured it. Here is where I am pulling the result.

![CleanShot 2021-11-12 at 09 35 56@2x](https://user-images.githubusercontent.com/51142180/141510473-b5a4c666-bed0-4c26-9b3f-ae98429edea8.png)
 
This is the authResult object returned:
![CleanShot 2021-11-12 at 09 30 05@2x](https://user-images.githubusercontent.com/51142180/141510012-010ff1ca-e2a9-4530-9f15-b6dbc524b2c6.png)


API rejection in postman: 
<img width="1256" alt="CleanShot 2021-11-12 at 09 34 41@2x" src="https://user-images.githubusercontent.com/51142180/141510246-6ae8f834-377e-4174-8995-d80230402e80.png">

Now if I setup the signin-options in the idpConfig object first (`loginStart.js`):
<img width="661" alt="CleanShot 2021-11-12 at 09 42 10@2x" src="https://user-images.githubusercontent.com/51142180/141511141-22e8def3-fe1c-431e-a4f0-422a1530af3e.png">


But I did so in the `uiConfig` object, under `signInOptions` in `webLogin.js`, but the results were the same with the above example of the `authResult`. So it still seems that we are only getting the Firebase Refresh Token back - which from what I read is unable to refresh the oauth token that is good for the Google APIs.
<img width="736" alt="CleanShot 2021-11-12 at 09 43 42@2x" src="https://user-images.githubusercontent.com/51142180/141511558-b9abe6f3-77dc-43b8-987a-a0dc259b98fb.png">

**Comment by david-asher** [comment]
This might work: staying on the browser script where you can use the Firebase Javascript library, 
https://firebase.google.com/docs/reference/js/auth.googleauthprovider.md#googleauthprovidercredentialfromresult
GoogleAuthProvider.credentialFromResult()
Used to extract the underlying OAuthCredential from a UserCredential.

**Comment by Calhistorian** [comment]
I can't seem to get the module initialized in `weblogin.js`. I can see that you have the modules loaded on the `loginstart.html` page, but can't seem to get the `credentialFromResult()` method to function on its own or on a new constructor instance. I guess I am just not really getting the firebase/auth namespace right? 

Any advice?

**Comment by david-asher** [comment]
This pattern may be helpful:
https://github.com/firebase/firebaseui-web/issues/476#issuecomment-411131605

**Comment by Calhistorian** [comment]
I still can't seem to get the function/method recognized. 

![CleanShot 2021-11-13 at 10 36 20@2x](https://user-images.githubusercontent.com/51142180/141655375-8b6bfccb-d967-4996-ac80-fb57577e1a45.png)


Whether I call GoogleAuthProvider() from `firebase.auth` or `firebase.auth()` it is not recognized as a function.

<img width="389" alt="CleanShot 2021-11-13 at 10 32 24@2x" src="https://user-images.githubusercontent.com/51142180/141655402-1f5a4c00-32ed-4bc9-b63b-4e2bf111456d.png">

So firebase is intialized, but the functions aren't available in this scope for some reason.

**Comment by david-asher** [comment]
The example in the last reference shows this usage pattern:
```
const provider = new firebase.auth.OAuthProvider('facebook.com');
const credential = provider.credential(null, 'FB_ACCESS_TOKEN');
....
// You are better off using the built in provider class.
const credential = firebase.auth.FacebookAuthProvider.credential( 'FB_ACCESS_TOKEN');
```

**Comment by Calhistorian** [comment]
I did follow that exactly but still getting the error that no function exists. This is why I was so confused - if I have the `firebase` initialized and can even pull the current user through `firebase.auth().currentUser`, than why is the `GoogleAuthprovider` method not being recognized as a function.

For example, with this it still errors out:
![CleanShot 2021-11-15 at 09 06 02@2x](https://user-images.githubusercontent.com/51142180/141823845-4e0750d4-fd67-47e2-ab3e-5b463931e5cd.png)

Result:
<img width="404" alt="CleanShot 2021-11-15 at 09 03 31@2x" src="https://user-images.githubusercontent.com/51142180/141823694-e0e955b1-a4f6-4993-8c74-331915fa197f.png">

I clearly have the firebase instance initialized since I can pull the current user correct? 

Now I thought perhaps its because I need to initialize the GoogleAuthProvider() constructor first (even though I am already getting the result from the signin flow. 

But with this code:
<img width="832" alt="CleanShot 2021-11-15 at 09 15 15@2x" src="https://user-images.githubusercontent.com/51142180/141825101-5b46ffbb-44c5-4177-9abb-9158eb55ebfa.png">


I get this error:
<img width="381" alt="CleanShot 2021-11-15 at 09 13 31@2x" src="https://user-images.githubusercontent.com/51142180/141824958-c40403c9-b002-4a6b-b318-117315580ca3.png">

This scope issue had always confused me here since you are calling the method in multiple places - for example on `loginstart.js`
<img width="615" alt="CleanShot 2021-11-15 at 09 24 28@2x" src="https://user-images.githubusercontent.com/51142180/141826606-eeab6ae5-066a-45b2-bc7d-0ced1af9af4e.png">

**Comment by david-asher** [comment]
At this point, I'd suggest posting to the [Firebase Google Group](https://groups.google.com/g/firebase-talk) and/or [Firebase Slack Channel](https://firebase-community.slack.com/archives/C0VPS2K0E) to see if anyone knows how to take a firebase token or user session and recover its corresponding OAuth token after the FirebaseUI workflow completes.

**Comment by Calhistorian** [comment]
My prior suspicions were confirmed (or at least the continued solution being presented) is to either do incremental authorization or using gapi signin method to sign into firebase at the same time. 

So I am going to attempt the latter. Thank you for all your help with what you have built here. Configuring to sign in to Firebase will be interesting.

**Comment by Calhistorian** [comment]
If I may ask a couple final questions about your package. 

First, I am interested in modifying/adding some functionality to the core node_module package, but naturally since I am using git those changes don't persist between machines due to .gitignore rules. If I were to transfer the core module functions/classes into the scripts folder and change the require/import refs, will it still work - or am I just asking for trouble? Looking to add some API routes and a few other small elements. Appreciate your quick thoughts. 

~~Second, I keep submitting my forms and despite having the requisite `e.preventDefault()` attached to the event, the app tries to navigate to the index.html page. The Form is in a modal, but just curious if you know if your framework requires special consideration in this regard.~~

Thanks again.

**Comment by david-asher** [comment]
If I follow your interest, you're looking to modify a function in a module. What I've usually done in these cases is to simply redefine the function. In Javascript, everything is a reference, and functions are really just strings that you can redefine at any time. Just set the function's reference, e.g. auth.gcpApi = function(requestOptions){ /* my new code here */ }

**Comment by Calhistorian** [comment]
Well that was easy enough. I will have to take a look with this different perspective. I think the one I was thinking about most was the register api functions in the `mainapp.js` module since they are initialized on startup. This gives me ideas. Wonderful. Thank you again.
