### ISSUE TITLE
Test Application - Force Reload Prevents App from ReLoading

### ISSUE THREAD

**Issue by Calhistorian** [david-asher/electron-firebase#11]
There are two instances worth mentioning where the opening spinner in the main browser window (`index.html`) never goes away. 

Any kind of reload of the application (without shutdown) halts the page content from displaying. Any idea what might be happening here?

**Comment by david-asher** [comment]
The 'app-ready' signal needs to be triggered as the final step in the login process that hides the main window spinner - this happens on indexpage_script.js ipc event handler. If this signal isn't generated, you have probably interrupted the browser sequence that would end with the POST API to logintoken. This happens in postAuthResult() in weblogin.js. So, I suggest making sure that the sequence is restored and postAuthResult() is called.
