### ISSUE TITLE
FATAL errors when performing 'npm install' in macOS terminal 

### ISSUE THREAD

**Issue by DevProjctX** [david-asher/electron-firebase#13]
npm ERR! path /Users/himanshugoyal/programming/electron-firebase/node_modules/lzma-native
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build && rimraf build
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR!   ACTION binding_gyp_liblzma_target_build .
npm ERR! /Library/Developer/CommandLineTools/usr/bin/make  all-recursive
npm ERR! Making all in src
npm ERR! Making all in liblzma
npm ERR! Making all in api
npm ERR! make[5]: Nothing to be done for `all'.

npm ERR! gyp ERR! cwd /Users/himanshugoyal/programming/electron-firebase/node_modules/lzma-native
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/himanshugoyal/programming/electron-firebase/node_modules/lzma-native/binding-v6.0.1-n-api-darwin-arm64/lzma_native.node --module_name=lzma_native --module_path=/Users/himanshugoyal/programming/electron-firebase/node_modules/lzma-native/binding-v6.0.1-n-api-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/himanshugoyal/programming/electron-firebase/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Darwin 20.6.0
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/himanshugoyal/programming/electron-firebase/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/himanshugoyal/programming/electron-firebase/node_modules/lzma-native
npm ERR! node-pre-gyp ERR! node -v v16.13.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.8
npm ERR! node-pre-gyp ERR! not ok

**Comment by david-asher** [comment]
Hi DevProjctX, you didn't give any context. This error looks like it's during installation, is that right, or were you performing a rebuild? Pretty much errors during installation would be a configuration problem on your platform. Which platform? Were there other npm modules installed? Please list the versions of tools dependencies and make sure they are all up to date (node, npm, node-gyp).

**Comment by DevProjctX** [comment]
Hi David, 

Yes i was trying to install 'electron-firebase' using 'npm install electron-firebase'. 

I updated npm and node recently and these are the versions.
node -v v16.13.2
node-gyp -v v8.3.0
npm -v v8.1.2
Chromium 96.0.4664.110, and 
Electron 16.0.7

I removed the node_modules folder before installation.
I am using M1 apple mac

**Comment by david-asher** [comment]
Looking just at the first errors, this isn't a direct install problem from electron-firebase but from a dependency. node-gyp is used by grpc in both electron and firebase - which is why it's one of the trickier dependencies and requires a rebuild of electron. The challenge here is that node-gyp isn't giving any context for where the failure is happening. You could try getting logs from the npm installation for more information: https://docs.npmjs.com/cli/v8/using-npm/logging
