### ISSUE TITLE
Error in sign in process

### ISSUE THREAD

**Issue by shubham2924** [david-asher/electron-firebase#14]
I followed the complete process flow as described in the documentation & when I hit npm start command, electron-firebase app started successfully with showing all the identity providers buttons(e.g facebook, google, github, etc). So I chose facebook sign in, after this facebook login window prompted(as I set up for facebook according to the documentation) I entered my login details of facebook & I even got signed in but then application abruptly got closed and when I again tried "npm start" then following windows were prompted :

![electron-firebase](https://user-images.githubusercontent.com/59010807/151603650-fcdc54a2-6559-4ce4-b798-d2fbfe45a09a.PNG)

And this is what was shown in the command line :
![electron-firebase-error-cmd](https://user-images.githubusercontent.com/59010807/151602880-a3865ea3-be1b-4266-b995-a3df0736ae95.PNG)

**Comment by david-asher** [comment]
A couple of things to look at, and it's almost always a configuration problem at this stage. There should be a Firebase function installed which handles custom token processing, and can be sensitive to configuration errors and will stop the signin process. You can check that in the Firebase Console: https://console.firebase.google.com/. Also you can set debugMode which might reveal more information: https://github.com/david-asher/electron-firebase#debugmode. This reported problem sounds like it may be the same as what you are experiencing: https://github.com/david-asher/electron-firebase/issues/8

**Comment by shubham2924** [comment]
okay, I'll have a check with the things you've mentioned, thanks for the reply !

**Comment by WillTaylor22** [comment]
I'm getting the same issue: `ERROR on signInNewUser:  Login failure`

In the Firebase Console the error message reads:
`Unhandled error { Error: IAM Service Account Credentials API has not been used in project 208408579649 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/iamcredentials.googleapis.com/overview?project=208408579649 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.; Please refer to https://firebase.google.com/docs/auth/admin/create-custom-tokens for more details on how to use and troubleshoot this feature.
    at FirebaseAuthError.FirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:44:28)
    at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/firebase-admin/lib/utils/error.js:90:28)
    at new FirebaseAuthError (/workspace/node_modules/firebase-admin/lib/utils/error.js:149:16)
    at Function.FirebaseAuthError.fromServerError (/workspace/node_modules/firebase-admin/lib/utils/error.js:188:16)
    at /workspace/node_modules/firebase-admin/lib/auth/token-generator.js:114:53
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errorInfo:
   { code: 'auth/insufficient-permission',
     message:
      'IAM Service Account Credentials API has not been used in project 208408579649 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/iamcredentials.googleapis.com/overview?project=208408579649 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.; Please refer to https://firebase.google.com/docs/auth/admin/create-custom-tokens for more details on how to use and troubleshoot this feature.' },
  codePrefix: 'auth' }`

However, I've followed that link and activated the API several hours ago.

My credentials are:
{
    "apiKey": "REDACTED",
    "authDomain": "neverlate-REDACTED.firebaseapp.com",
    "databaseURL": "",
    "projectId": "neverlate-REDACTED",
    "storageBucket": "neverlate-REDACTED.appspot.com",
    "messagingSenderId": "REDACTED",
    "appId": "1:208408579649REDACTED",
    "hostingUrl": "",
    "serviceAccountId": "firebase-adminsdk-REDACTED@neverlate-REDACTED.iam.gserviceaccount.com"
}

My console (with debug mode enabled) reads:

`REQUEST (REDACTED):  {
  protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'us-central1-neverlate-REDACTED.cloudfunctions.net',
  port: null,
  hostname: 'us-central1-neverlate-REDACTED.cloudfunctions.net',
  hash: null,
  search: null,
  query: null,
  pathname: '/customToken',
  path: '/customToken',
  href: 'https://us-central1-neverlate-REDACTED.cloudfunctions.net/customToken',
  method: 'POST',
  headers: [Object: null prototype] {
    'Content-Type': [ 'application/json' ],
    Accept: [ '*/*' ],
    'Content-Length': [ '165' ],
    'User-Agent': [ 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)' ],
    'Accept-Encoding': [ 'gzip,deflate' ],
    Connection: [ 'close' ]
  },
  agent: undefined
}
signInNewUser:  HttpsErrorImpl: INTERNAL
`

**Comment by david-asher** [comment]
Hi WillTaylor22, The symptoms you are describing do seem to point to an IAM configuration problem. Have you worked through the troubleshooting section of the custom tokens documentation?
https://firebase.google.com/docs/auth/admin/create-custom-tokens#troubleshooting
