### ISSUE TITLE
Example application creation doesn't work

### ISSUE THREAD

**Issue by piccinnigius** [david-asher/electron-firebase#2]
Hi!
i've tryed this command with npm and yarn but it creates only a new package json and not the full example app.

```
# install the electron-firebase framework and example application
npm install electron-firebase
```

Where i'm failing?

Thanks so much

**Comment by david-asher** [comment]
Hi - The electron-firebase installation process was never tested with yarn. Assuming everything installed with npm as usual, then the only next step is to run the script at ./install_app/postinstall.js - you should be able to run that from node at the root folder of your project.

**Comment by piccinnigius** [comment]
Thanks so much @david-asher , my fault. yarn init breaks the process. Running from the beginning with npm works!
Thanks again for this repo!
