### ISSUE TITLE
Build Fails but files added regardless ( also package != application)

### ISSUE THREAD

**Issue by Lite5h4dow** [david-asher/electron-firebase#3]
Installing via `yarn add electron-firebase` produces this error
```
make: Entering directory '/home/lotus/Projects/Personal Projects/NuzlockeLegends-Electron/node_modules/sse4_crc32/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/sse42/src/sse42.o
  AR(target) Release/obj.target/sse42.a
  COPY Release/sse42.a
  CXX(target) Release/obj.target/crc32c/src/crc32c.o
g++: error: Projects/NuzlockeLegends-Electron/node_modules/node-addon-api: No such file or directory
make: *** [crc32c.target.mk:114: Release/obj.target/crc32c/src/crc32c.o] Error 1
make: Leaving directory '/home/lotus/Projects/Personal Projects/NuzlockeLegends-Electron/node_modules/sse4_crc32/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/lotus/.nvm/versions/node/v15.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
gyp ERR! System Linux 4.19.128-microsoft-standard
gyp ERR! command \"/home/lotus/.nvm/versions/node/v15.1.0/bin/node\" \"/home/lotus/.nvm/versions/node/v15.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /home/lotus/Projects/Personal Projects/NuzlockeLegends-Electron/node_modules/sse4_crc32
```
however the module adds files to the root of my project

**Comment by Lite5h4dow** [comment]
also, why is a module adding files to my already constructed project? firebaserc config file I can understand, but replace my package.conf and adding files and folders to the root of my project directory just gives me more cleanup to do.

I already have my functions defined and deployed in another project. I don't need the pages, I've already made my own backend server, all I want is the backend firebase functionality. if you're making a template project, make this git repo a template repo for people to build from or use the npx deploy process. don't make it an NPM package. NPM packages are used as packages. not whole ass projects

**Comment by david-asher** [comment]
Thank you for the feedback and suggestion. Electron-firebase was not tested for use with yarn; the installation process is documented in detail and recommends to start with an empty project folder for this reason. Selecting subcomponents was not a consideration for the design as it was intended as a quick-start framework to a new app, as documented.
