### ISSUE TITLE
Npm install electron-firebase messes up npm on windows 10

### ISSUE THREAD

**Issue by Am3nd** [david-asher/electron-firebase#7]
After I installed electron-firebase I was unable to run any npm commands in its directory and for any other projects that were using npm, yarn works fine it was just npm. I checked using the integrated terminal for vscode and also cmd. Both did not work. I had to spend all last night restoring to my last backup I didn't know what had caused the issue at the time. Thankfully I do daily backups but like an Idiot, I tried reinstalling electron-firebase and the same thing happened. I'm going to have to restore this morning's backup, I am not looking forward to it.

**Comment by david-asher** [comment]
I've never experienced an npm misconfiguration on any platform and no one has reported it. Electron-firebase does not use yarn.

It would be helpful if you could give some details:
- what platform are you working on?
- what were the node.js and npm versions before you started?
- did the electron-firebase installation show any errors?
- did you start with a new project or an existing project?

It would also be helpful if you had a console log available that you could share, with commands and installation output.

You can see all of the dependent packages in the package.json file:
https://github.com/david-asher/electron-firebase/blob/master/package.json

And then the loading of firebase-tools and other configurations in the postinstall.js script:
https://github.com/david-asher/electron-firebase/blob/master/install_app/postinstall.js

So there's nothing obvious that would muck up the operation of npm, and I would have expected in any case that a reload of npm could solve your configuration problem without a system restore. We should be able to isolate what happened on your system and make this process far easier for you.

**Comment by Am3nd** [comment]
Hi David,

Thank you for responding, you're right I should have reinstalled npm before doing a system restore. That's what I did the second time around. I reinstalled NPM and now it works fine. As soon as I ran npm install electron-firebase, I was unable to run any npm run "scripts" commands. The output would seem likes it's running however nothing shows up or is executed. It occurs system-wide, in other projects, and npm doesn't work with cmd as well. However, since I reinstalled npm it nows runs fine and I am no longer facing any issues. 

Output
```
C:\Users\ibnmu\LocalCode\FirebaseV2>npm install electron-firebae
....

C:\Users\ibnmu\LocalCode\FirebaseV2>npm start

  > firebasev2@1.0.0 start
  > electron ./main.js
C:\Users\ibnmu\LocalCode\FirebaseV2>

```

**Comment by david-asher** [comment]
Thanks for sharing this information. Looking for a simple explanation, my best guess would be that your PATH environment variable was changed in a way that misdirects from your npm binary location. There is nothing in the electron-firebase installation that explicitly changes the PATH, but it's possible that a dependency could do that. You could check by printing out the PATH variable before and after installation. There may also be some interaction between yarn and the PATH variable that I'm not aware of.

**Comment by Am3nd** [comment]
Thank you for your help David, I appreciate it! I should have probably just reinstalled npm before doing a system restore, I was probably more anxious to finally use the daily backups I have been making for the last couple of years lol. I'm going to close this, in case anyone else has this issue please try reinstalling npm and that should fix the problem.
