### ISSUE TITLE
Google Sign-In Fails with Test Application

### ISSUE THREAD

**Issue by Calhistorian** [david-asher/electron-firebase#8]
So I was able to get everything installed and running on my iMac. Everything loads fine. Test application loads. However authentication fails using Google Sign-In. I would try others if I need to. But I only want Google Sign-In anyway. 

Error:
```
signInNewUser:  HttpsErrorImpl: INTERNAL
    at new HttpsErrorImpl (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/@firebase/functions/dist/index.node.cjs.js:62:28)
    at _errorForResponse (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/@firebase/functions/dist/index.node.cjs.js:157:12)
    at Service.<anonymous> (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/@firebase/functions/dist/index.node.cjs.js:610:33)
    at step (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'internal',
  details: undefined
}
ERROR on signInNewUser:  Login failure
```

In setting up the authentication I just added the Google signin method and email. I attempted to sign in using two different Google accounts and an email/password combo just to make sure, but all three failed.

Both accounts that I used to signin do show up in the "Users" section and have their assigned UID's. I am assuming that the token is just not be returned appropriately into the application.

Looking at the Cloud Functions:

The Error Logs have this:

```
errorInfo:
code: auth/insufficient-permission
```

The service account does have "Service Account Token Creator" as a role. 

Perhaps I just need to wait a bit longer, but its been about an hour.

**Comment by david-asher** [comment]
Usually if you got to this point then the Google login worked correctly, can you verify that? It should look like signing into gmail or any other Google app. 

This phase of login is passing the user credentials, collected from the Browser (renderer) process to the Main (node.js) process. This is the part that uses the customToken function hosted in firebase cloud - so we need to believe the error message from the cloud function error log. 

I suspect that even though "everything loads fine" there is still a misconfiguration.

If you edit config/app-config.json and set `"debugMode": true,` we can get more detailed information.

**Comment by Calhistorian** [comment]
Here is the error after turning on debugging:

```
REQUEST (1634923689564):  {
  protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'us-central1-********.cloudfunctions.net',
  port: null,
  hostname: 'us-central1-********.cloudfunctions.net',
  hash: null,
  search: null,
  query: null,
  pathname: '/customToken',
  path: '/customToken',
  href: 'https://us-central1-********.cloudfunctions.net/customToken',
  method: 'POST',
  headers: [Object: null prototype] {
    'Content-Type': [ 'application/json' ],
    Accept: [ '*/*' ],
    'Content-Length': [ '181' ],
    'User-Agent': [ 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)' ],
    'Accept-Encoding': [ 'gzip,deflate' ],
    Connection: [ 'close' ]
  },
  agent: undefined
}
signInNewUser:  HttpsErrorImpl: INTERNAL
    at new HttpsErrorImpl (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/@firebase/functions/dist/index.node.cjs.js:62:28)
    at _errorForResponse (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/@firebase/functions/dist/index.node.cjs.js:157:12)
    at Service.<anonymous> (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/@firebase/functions/dist/index.node.cjs.js:610:33)
    at step (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'internal',
  details: undefined
}
ERROR on signInNewUser:  Login failure
```

Same error in the cloud function error reporting as well:

```
Unhandled error { Error: The caller does not have permission;
```

**Comment by david-asher** [comment]
One suspect would be the content security policy, but *.cloudfunctions.net has been included (it's in config/content-security-policy.net) so I don't want to pursue that yet. Another suspect is the user-agent string, but I would need to do some tracing to find out if that is normal. But the REQUEST doesn't contain a payload, and again I'll need to compare this against a normal trace. I'm not available for a few days, so I may get to respond on 10/25 or 26. Thanks for proving this error log, that should be helpful.

**Comment by david-asher** [comment]
The request to customToken looks perfect, but at this point we don't have enough information logged to isolate what parameter is missing or invalid. Since I don't have your configuration and can't reproduce the error that you're seeing, I hope you wouldn't mind a little debugging. Please replace the try{} block in lib/authentication.js line 124 with the following. If you want to send a private response with the output, look up my GitHub profile, then LinkedIn has contact info.

```
   try {
        // keep the new user object for global access throughout the app
        global.user = newUser.user

        // make remote call to firebase function customToken
        const getToken = firebase.functions().httpsCallable('customToken')
        const customTokenParams = { 
            userid: newUser.user.uid, 
            serviceAccountId: global.fbConfig.serviceAccountId,
            projectId: global.fbConfig.projectId
        }

        // !!DEBUG
        console.log( "customTokenParams = ", customTokenParams )

        const result = await getToken( customTokenParams )

        // !!DEBUG
        console.log( "customToken result = ", result.data )

        // pass the custom token to firebase to sign in
        const userToken = await firebase.auth().signInWithCustomToken( result.data )

        // !!DEBUG
        console.log( "userToken = ", userToken )

        // returns a UserCredential: https://firebase.google.com/docs/reference/node/firebase.auth#usercredential
        return userToken.user
    }

```

**Comment by Calhistorian** [comment]
I will do so.

First, however, after following the instillation instructions very closely it is now clear that the nom install of electron-firebase was not complete. I do not have the /lib /docs /install_app /tests folders in my project (as they are in the Github files). I had suspected this was intentional, but now that you are suggesting to modify something in the /lib folder, clearly there was a problem.

**Comment by david-asher** [comment]
I should have been more specific. What you say is a normal installation. Please look inside the node_modules folder for the electron-firebase package.

**Comment by Calhistorian** [comment]
No private response at this point is required. Its a dummy account anyway. And I can confirm that the serviceAccountId has the "Service Account Token Creator" role.

Error: 

```
customTokenParams =  {
  userid: 
  serviceAccountId: 
  projectId: 
}
REQUEST (1635268277813):  {
  protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'us-central1-electron-firebase-8cd5e.cloudfunctions.net',
  port: null,
  hostname: 'us-central1-electron-firebase-8cd5e.cloudfunctions.net',
  hash: null,
  search: null,
  query: null,
  pathname: '/customToken',
  path: '/customToken',
  href: 'https://us-central1-electron-firebase-8cd5e.cloudfunctions.net/customToken',
  method: 'POST',
  headers: [Object: null prototype] {
    'Content-Type': [ 'application/json' ],
    Accept: [ '*/*' ],
    'Content-Length': [ '181' ],
    'User-Agent': [ 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)' ],
    'Accept-Encoding': [ 'gzip,deflate' ],
    Connection: [ 'close' ]
  },
  agent: undefined
}
signInNewUser:  HttpsErrorImpl: INTERNAL
    at new HttpsErrorImpl (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/@firebase/functions/dist/index.node.cjs.js:62:28)
    at _errorForResponse (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/@firebase/functions/dist/index.node.cjs.js:157:12)
    at Service.<anonymous> (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/@firebase/functions/dist/index.node.cjs.js:610:33)
    at step (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/Users/markrobertson/Projects/Github/Electron-Firebase/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'internal',
  details: undefined
}
ERROR on signInNewUser:  Login failure
```

**Comment by Calhistorian** [comment]
There is also an error in the renderer process, but I can't access it under the dialogue

**Comment by david-asher** [comment]
Thanks for making the effort to go through this, which is very helpful. At this point the failure is exactly at the call to customToken, which is all in the hands of firebase cloud functions. I will need to look more closely at what dependencies are required and get back to you, but it looks like we never really got to a stable installation of the cloud function.

**Comment by Calhistorian** [comment]
Thank you. Appreciate the help. Would it be possible to manually install instead? I have never used Firebase, so not so sure.

**Comment by david-asher** [comment]
Let's get a look at the error log for customToken, it should have a more specific error. Go to the firebase console Project Overview, Build, Functions -> Logs.

**Comment by david-asher** [comment]
There is one critical difference that I see - under Service Account Token Creator role, I have a second entry. In your case it would assign electron-firebase-8cd5e@appspot.gserviceaccount.com to App Engine default service account. Or in other words, your project has Editor role but also needs to have Service Account Token Creator role.

**Comment by david-asher** [comment]
The permission failure is relating to this option in the customToken documentation:
https://firebase.google.com/docs/auth/admin/create-custom-tokens#using_a_service_account_id

Your serviceAccountId seems to be intact, so let's look at the last sentence for your error condition:

`Moreover, you must also make sure that the service account the Admin SDK is using to make this call —usually {project-name}@appspot.gserviceaccount.com— has the iam.serviceAccounts.signBlob permission. See the troubleshooting section below for more details.`

**Comment by Calhistorian** [comment]
I did follow these instructions, since the Token Creator role allows for the `signBlob` permissions. However, I went ahead and added the Token Creator role to the other project service accounts and it now works! I will be removing some to identify which one really was missing the permissions. As you can imagine, documentation can never cover ever outlier or variation. Thank you again for your help with this. I will let you know when we release so that you might see what we have brewing - small but useful.

**Comment by david-asher** [comment]
Great to hear that you are up and running! I can update the documentation to check on the signBlob permission. Thank you for sticking with this process. Yes it would be fantastic to see what you are up to!
