### ISSUE TITLE
[Question] Building and packing

### ISSUE THREAD

**Issue by jonybur** [david-asher/electron-firebase#9]
Hello,

I've been trying to build and generate a .dmg file from this boilerplate. Unfortunately it seems to not be working for me, I've tried several ways of doing so. I have tried electron-builder and other methods but with no avail, the base boilerplate application closes itself as soon as the .app is opened. 

What's the preferred method to build and pack this boilerplate?

I am aware that the root ./main.js file is the main process entry file, but which one would be the entry file for the renderer process?

Thanks

**Comment by jonybur** [comment]
Solved!

**Comment by Calhistorian** [comment]
> Solved!

@jonybur How did you solve this problem? Having a similar issue.
